# Generated by Django 5.1.5 on 2025-01-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='', upload_to='G:\\Programming\\Cinema/images/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(default='', upload_to='G:\\Programming\\Cinema/images/'),
        ),
    ]
