# Generated by Django 5.1.5 on 2025-01-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_actor_image_alter_director_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='film',
        ),
        migrations.AddField(
            model_name='session',
            name='film',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.film'),
        ),
    ]
