import datetime


actors_data = [
        {'name': 'Вайнона Райдер', 'birthday': datetime.datetime(1971, 10, 29), 'sex': 'female',
         'image': 'Вайнона_Райдер.jpg'},
        {'name': 'Джонни Депп', 'birthday': datetime.datetime(1963, 6, 9), 'sex': 'male', 'image': 'Джонни_Депп.jpg'},
        {'name': 'Джеймс Спейдер', 'birthday': datetime.datetime(1960, 2, 7), 'sex': 'male',
         'image': 'Джеймс_Спейдер.jpg'},
        {'name': 'Эмма Уотсон', 'birthday': datetime.datetime(1990, 4, 15), 'sex': 'female',
         'image': 'Эмма_Уотсон.jpg'},
        {'name': 'Бенедикт Камбербэтч', 'birthday': datetime.datetime(1976, 7, 19), 'sex': 'male',
         'image': 'Бенедикт_Камбербэтч.jpg'},
        {'name': 'Киану Ривз', 'birthday': datetime.datetime(1964, 9, 2), 'sex': 'male', 'image': 'Киану_Ривз.jpg'},
        {'name': 'Уилл Смит', 'birthday': datetime.datetime(1968, 9, 25), 'sex': 'male', 'image': 'Уилл_Смит.jpg'},
        {'name': 'Леонардо ДиКаприо', 'birthday': datetime.datetime(1974, 11, 11), 'sex': 'male',
         'image': 'Леонардо_ДиКаприо.jpg'},
        {'name': 'Марго Робби', 'birthday': datetime.datetime(1990, 7, 2), 'sex': 'female', 'image': 'Марго_Робби.jpg'},
        {'name': 'Анджелина Джоли', 'birthday': datetime.datetime(1975, 6, 4), 'sex': 'female',
         'image': 'Анджелина_Джоли.jpg'},
        {'name': 'Меган Фокс', 'birthday': datetime.datetime(1986, 5, 16), 'sex': 'female', 'image': 'Меган_Фокс.jpg'},
    ]

directors_data = [
    {'name': 'Тим Бёртон', 'birthday': datetime.datetime(1958, 8, 25), 'sex': 'male', 'image': 'Тим_Бёртон.jpg'},
    {'name': 'Грета Гервиг', 'birthday': datetime.datetime(1983, 8, 4), 'sex': 'female', 'image': 'Грета_Гервиг.jpg'},
    {'name': 'Джонатан Дэми', 'birthday': datetime.datetime(1944, 4, 22), 'sex': 'male', 'image': 'Джонатан_Дэми.jpg'},
    {'name': 'Джон К. Ричардсон', 'birthday': datetime.datetime(1962, 3, 5), 'sex': 'male', 'image': 'Джон_К_Ричардсон.jpg'},
    {'name': 'Джеймс Кэмерон', 'birthday': datetime.datetime(1954, 8, 16), 'sex': 'male', 'image': 'Джеймс_Кэмерон.jpg'},
    {'name': 'Ник Кассаветис', 'birthday': datetime.datetime(1959, 5, 9), 'sex': 'male', 'image': 'Ник_Кассаветис.jpg'},
    {'name': 'Брюс Робинсон', 'birthday': datetime.datetime(1946, 5, 23), 'sex': 'male', 'image': 'Брюс_Робинсон.jpg'},
    {'name': 'Гор Вербински', 'birthday': datetime.datetime(1961, 3, 16), 'sex': 'male', 'image': 'Гор_Вербински.jpg'},
    {'name': 'Хоаким Роннинг', 'birthday': datetime.datetime(1972, 5, 30), 'sex': 'male', 'image': 'Хоаким_Роннинг.jpg'},
    {'name': 'Эспен Сандберг', 'birthday': datetime.datetime(1972, 7, 15), 'sex': 'male', 'image': 'Эспен_Сандберг.jpg'},
    {'name': 'Кертис Хансон', 'birthday': datetime.datetime(1945, 3, 24), 'sex': 'male', 'image': 'Кертис_Хансон.jpg'},
    {'name': 'Стивен Содерберг', 'birthday': datetime.datetime(1963, 1, 14), 'sex': 'male', 'image': 'Стивен_Содерберг.jpg'},
    {'name': 'Джон Бокенкамп', 'birthday': datetime.datetime(1974, 3, 22), 'sex': 'male', 'image': 'Джон_Бокенкамп.jpg'},
    {'name': 'Винсент Д’Онфре', 'birthday': datetime.datetime(1973, 11, 16), 'sex': 'male', 'image': 'Винсент_Д’Онфре.jpg'},
    {'name': 'Квентин Тарантино', 'birthday': datetime.datetime(1963, 3, 27), 'sex': 'male', 'image': 'Квентин_Тарантино.jpg'},
    {'name': 'Джон Херцфельд', 'birthday': datetime.datetime(1950, 6, 1), 'sex': 'male', 'image': 'Джон_Херцфельд.jpg'},
    {'name': 'Альфонсо Куарон', 'birthday': datetime.datetime(1961, 11, 28), 'sex': 'male', 'image': 'Альфонсо_Куарон.jpg'},
    {'name': 'Майк Ньюэлл', 'birthday': datetime.datetime(1942, 3, 28), 'sex': 'male', 'image': 'Майк_Ньюэлл.jpg'},
    {'name': 'Дэвид Йейтс', 'birthday': datetime.datetime(1963, 11, 30), 'sex': 'male', 'image': 'Дэвид_Йейтс.jpg'},
    {'name': 'Билл Кондон', 'birthday': datetime.datetime(1955, 10, 22), 'sex': 'male', 'image': 'Билл_Кондон.jpg'},
    {'name': 'Марк Гэтисс', 'birthday': datetime.datetime(1966, 10, 17), 'sex': 'male', 'image': 'Марк_Гэтисс.jpg'},
    {'name': 'Стивен Моффат', 'birthday': datetime.datetime(1961, 11, 18), 'sex': 'male', 'image': 'Стивен_Моффат.jpg'},
    {'name': 'Скотт Дерриксон', 'birthday': datetime.datetime(1966, 7, 16), 'sex': 'male', 'image': 'Скотт_Дерриксон.jpg'},
    {'name': 'Мортен Тильдум', 'birthday': datetime.datetime(1967, 5, 19), 'sex': 'male', 'image': 'Мортен_Тильдум.jpg'},
    {'name': 'Джозеф Эдгар', 'birthday': datetime.datetime(1970, 5, 22), 'sex': 'male', 'image': 'Джозеф_Эдгар.jpg'},
    {'name': 'Стивен Спилберг', 'birthday': datetime.datetime(1946, 12, 18), 'sex': 'male', 'image': 'Стивен_Спилберг.jpg'},
    {'name': 'Лана Вачовски', 'birthday': datetime.datetime(1965, 6, 21), 'sex': 'female', 'image': 'Лана_Вачовски.jpg'},
    {'name': 'Лилли Вачовски', 'birthday': datetime.datetime(1967, 12, 29), 'sex': 'female', 'image': 'Лилли_Вачовски.jpg'},
    {'name': 'Чад Стахелски', 'birthday': datetime.datetime(1968, 9, 20), 'sex': 'male', 'image': 'Чад_Стахелски.jpg'},
    {'name': 'Ян Де Бонт', 'birthday': datetime.datetime(1946, 10, 22), 'sex': 'male', 'image': 'Ян_Де_Бонт.jpg'},
    {'name': 'Фрэнсис Лоуренс', 'birthday': datetime.datetime(1971, 3, 26), 'sex': 'male', 'image': 'Фрэнсис_Лоуренс.jpg'},
    {'name': 'Джонатан Левин', 'birthday': datetime.datetime(1970, 6, 2), 'sex': 'male', 'image': 'Джонатан_Левин.jpg'},
    {'name': 'Джеймс Манголд', 'birthday': datetime.datetime(1963, 12, 16), 'sex': 'male', 'image': 'Джеймс_Манголд.jpg'},
    {'name': 'Роберт Стромберг', 'birthday': datetime.datetime(1958, 6, 5), 'sex': 'male', 'image': 'Роберт_Стромберг.jpg'},
    {'name': 'Трэвис Найт', 'birthday': datetime.datetime(1973, 10, 13), 'sex': 'male', 'image': 'Трэвис_Найт.jpg'},
    {'name': 'Дэвид Эйр', 'birthday': datetime.datetime(1968, 3, 18), 'sex': 'male', 'image': 'Дэвид_Эйр.jpg'},
    {'name': 'Саймон Уэст', 'birthday': datetime.datetime(1961, 7, 3), 'sex': 'male', 'image': 'Саймон_Уэст.jpg'},
    {'name': 'Майкл Бэй', 'birthday': datetime.datetime(1965, 2, 17), 'sex': 'male', 'image': 'Майкл_Бэй.jpg'},
    {'name': 'Джеймс МакТиг', 'birthday': datetime.datetime(1970, 1, 5), 'sex': 'male', 'image': 'Джеймс_МакТиг.jpg'}
]

films_data = [
    # Вайнона Райдер
    {'title': 'Битлджус', 'director': 'Тим Бёртон', 'genres': ['комедия', 'фэнтези'], 'actors': ['Вайнона Райдер'],
     'release_date': '1988-03-30', 'duration': 92},
    {'title': 'Маленькие женщины', 'director': 'Грета Гервиг', 'genres': ['драма', 'романтика'],
     'actors': ['Вайнона Райдер'], 'release_date': '1994-12-25', 'duration': 118},
    {'title': 'Странные дела', 'director': 'Джонатан Дэми', 'genres': ['драма', 'триллер'],
     'actors': ['Вайнона Райдер'], 'release_date': '2016-07-15', 'duration': 50},
    {'title': 'Дорога на Геллоуэй', 'director': 'Джон К. Ричардсон', 'genres': ['драма'], 'actors': ['Вайнона Райдер'],
     'release_date': '1999-04-16', 'duration': 112},
    {'title': 'Чужие', 'director': 'Джеймс Кэмерон', 'genres': ['фантастика', 'ужасы'], 'actors': ['Вайнона Райдер'],
     'release_date': '1986-07-18', 'duration': 137},
    {'title': 'Дневник памяти', 'director': 'Ник Кассаветис', 'genres': ['драма', 'романтика'],
     'actors': ['Вайнона Райдер'], 'release_date': '2004-06-25', 'duration': 123},
    {'title': 'Долгий путь домой', 'director': 'Джон К. Ричардсон', 'genres': ['драма'], 'actors': ['Вайнона Райдер'],
     'release_date': '2001-11-23', 'duration': 106},
    {'title': 'Сумасшедшая свадьба', 'director': 'Джонатан Левин', 'genres': ['комедия', 'романтика'],
     'actors': ['Вайнона Райдер'], 'release_date': '2014-05-16', 'duration': 94},

    # Джонни Депп
    {'title': 'Сумасшедший шляпник', 'director': 'Тим Бёртон', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Джонни Депп'], 'release_date': '2010-03-05', 'duration': 108},
    {'title': 'Чарли и шоколадная фабрика', 'director': 'Тим Бёртон', 'genres': ['фэнтези', 'комедия'],
     'actors': ['Джонни Депп'], 'release_date': '2005-07-15', 'duration': 115},
    {'title': 'Тёмные тени', 'director': 'Тим Бёртон', 'genres': ['комедия', 'фэнтези'], 'actors': ['Джонни Депп'],
     'release_date': '2012-05-11', 'duration': 113},
    {'title': 'Ромовый дневник', 'director': 'Брюс Робинсон', 'genres': ['комедия', 'драма'], 'actors': ['Джонни Депп'],
     'release_date': '2011-10-28', 'duration': 120},
    {'title': 'Пираты Карибского моря: На краю света', 'director': 'Гор Вербински',
     'genres': ['приключения', 'фэнтези'], 'actors': ['Джонни Депп'], 'release_date': '2007-05-25', 'duration': 169},
    {'title': 'Пираты Карибского моря: Мертвецы не рассказывают сказки', 'director': 'Хоаким Роннинг, Эспен Сандберг',
     'genres': ['приключения', 'фэнтези'], 'actors': ['Джонни Депп'], 'release_date': '2017-05-26', 'duration': 129},
    {'title': 'Секреты Лос-Анджелеса', 'director': 'Кертис Хансон', 'genres': ['криминал', 'драма'],
     'actors': ['Джонни Депп'], 'release_date': '1997-09-19', 'duration': 138},

    # Джеймс Спейдер
    {'title': 'Секс, ложь и видео', 'director': 'Стивен Содерберг', 'genres': ['драма'], 'actors': ['Джеймс Спейдер'],
     'release_date': '1989-08-04', 'duration': 100},
    {'title': 'Черный список', 'director': 'Джон Бокенкамп', 'genres': ['криминал', 'драма', 'триллер'],
     'actors': ['Джеймс Спейдер'], 'release_date': '2013-09-23', 'duration': 43},
    {'title': 'Стеклянный замок', 'director': "Винсент Д'Онфре", 'genres': ['драма', 'семейный'],
     'actors': ['Джеймс Спейдер'], 'release_date': '2017-08-11', 'duration': 127},
    {'title': 'Убить Билла', 'director': 'Квентин Тарантино', 'genres': ['экшн', 'триллер'],
     'actors': ['Джеймс Спейдер'], 'release_date': '2003-10-10', 'duration': 111},
    {'title': 'Призрак', 'director': 'Джон Херцфельд', 'genres': ['драма', 'триллер'], 'actors': ['Джеймс Спейдер'],
     'release_date': '1996-09-27', 'duration': 110},

    # Эмма Уотсон
    {'title': 'Гарри Поттер и философский камень', 'director': 'Крис Коламбус', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Эмма Уотсон'], 'release_date': '2001-11-16', 'duration': 152},
    {'title': 'Гарри Поттер и тайная комната', 'director': 'Крис Коламбус', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Эмма Уотсон'], 'release_date': '2002-11-15', 'duration': 161},
    {'title': 'Гарри Поттер и узник Азкабана', 'director': 'Альфонсо Куарон', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Эмма Уотсон'], 'release_date': '2004-06-04', 'duration': 142},
    {'title': 'Гарри Поттер и Кубок огня', 'director': 'Майк Ньюэлл', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Эмма Уотсон'], 'release_date': '2005-11-18', 'duration': 157},
    {'title': 'Гарри Поттер и Орден Феникса', 'director': 'Дэвид Йейтс', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Эмма Уотсон'], 'release_date': '2007-07-11', 'duration': 138},
    {'title': 'Гарри Поттер и Принц-полукровка', 'director': 'Дэвид Йейтс', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Эмма Уотсон'], 'release_date': '2009-07-15', 'duration': 153},
    {'title': 'Гарри Поттер и Дары Смерти: Часть 1', 'director': 'Дэвид Йейтс', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Эмма Уотсон'], 'release_date': '2010-11-19', 'duration': 146},
    {'title': 'Гарри Поттер и Дары Смерти: Часть 2', 'director': 'Дэвид Йейтс', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Эмма Уотсон'], 'release_date': '2011-07-15', 'duration': 130},
    {'title': 'Красавица и чудовище', 'director': 'Билл Кондон', 'genres': ['фэнтези', 'музыка'],
     'actors': ['Эмма Уотсон'], 'release_date': '2017-03-17', 'duration': 129},

    # Бенедикт Камбербэтч
    {'title': 'Шерлок', 'director': 'Марк Гэтисс, Стивен Моффат', 'genres': ['криминал', 'драма', 'мистика'],
     'actors': ['Бенедикт Камбербэтч'], 'release_date': '2010-07-25', 'duration': 90},
    {'title': 'Доктор Стрэндж', 'director': 'Скотт Дерриксон', 'genres': ['фантастика', 'экшн'],
     'actors': ['Бенедикт Камбербэтч'], 'release_date': '2016-11-04', 'duration': 115},
    {'title': 'Игра в имитацию', 'director': 'Мортен Тильдум', 'genres': ['биография', 'драма', 'исторический'],
     'actors': ['Бенедикт Камбербэтч'], 'release_date': '2014-11-28', 'duration': 113},
    {'title': 'Тёмные времена', 'director': 'Джозеф Эдгар', 'genres': ['драма', 'исторический'],
     'actors': ['Бенедикт Камбербэтч'], 'release_date': '2017-12-22', 'duration': 125},
    {'title': 'Война миров', 'director': 'Стивен Спилберг', 'genres': ['фантастика', 'экшн'],
     'actors': ['Бенедикт Камбербэтч'], 'release_date': '2005-06-29', 'duration': 116},

    # Киану Ривз
    {'title': 'Матрица', 'director': 'Лана и Лилли Вачовски', 'genres': ['фантастика', 'экшн'],
     'actors': ['Киану Ривз'], 'release_date': '1999-03-31', 'duration': 136},
    {'title': 'Джон Уик', 'director': 'Чад Стахелски', 'genres': ['экшн', 'триллер'], 'actors': ['Киану Ривз'],
     'release_date': '2014-10-24', 'duration': 101},
    {'title': 'Скорость', 'director': 'Ян Де Бонт', 'genres': ['экшн', 'триллер'], 'actors': ['Киану Ривз'],
     'release_date': '1994-06-10', 'duration': 116},
    {'title': 'Константин', 'director': 'Фрэнсис Лоуренс', 'genres': ['фантастика', 'ужасы'], 'actors': ['Киану Ривз'],
     'release_date': '2005-02-18', 'duration': 121},
    {'title': 'Билли Бейтс', 'director': 'Джонатан Левин', 'genres': ['драма', 'комедия'], 'actors': ['Киану Ривз'],
     'release_date': '2013-04-01', 'duration': 88},

    # Уилл Смит
    {'title': 'Люди в черном', 'director': 'Барри Зонненфельд', 'genres': ['фантастика', 'комедия'],
     'actors': ['Уилл Смит'], 'release_date': '1997-07-02', 'duration': 98},
    {'title': 'В погоне за счастьем', 'director': 'Габриэле Муччино', 'genres': ['драма', 'биография'],
     'actors': ['Уилл Смит'], 'release_date': '2006-12-15', 'duration': 117},
    {'title': 'Я, легенда', 'director': 'Фрэнсис Лоуренс', 'genres': ['фантастика', 'ужасы', 'драма'],
     'actors': ['Уилл Смит'], 'release_date': '2007-12-14', 'duration': 101},
    {'title': 'Альфа', 'director': 'Альберт Хьюз', 'genres': ['приключения', 'драма'], 'actors': ['Уилл Смит'],
     'release_date': '2018-08-17', 'duration': 96},

    # Леонардо ДиКаприо
    {'title': 'Титаник', 'director': 'Джеймс Кэмерон', 'genres': ['драма', 'романтика'],
     'actors': ['Леонардо ДиКаприо'], 'release_date': '1997-12-19', 'duration': 195},
    {'title': 'Начало', 'director': 'Кристофер Нолан', 'genres': ['фантастика', 'экшн'],
     'actors': ['Леонардо ДиКаприо'], 'release_date': '2010-07-16', 'duration': 148},
    {'title': 'Волк с Уолл-стрит', 'director': 'Мартин Скорсезе', 'genres': ['комедия', 'биография', 'драма'],
     'actors': ['Леонардо ДиКаприо'], 'release_date': '2013-12-25', 'duration': 180},
    {'title': 'Выживший', 'director': 'Алехандро Гонсалес Иньярриту', 'genres': ['драма', 'приключения'],
     'actors': ['Леонардо ДиКаприо'], 'release_date': '2015-12-25', 'duration': 156},
    {'title': 'Остров проклятых', 'director': 'Мартин Скорсезе', 'genres': ['триллер', 'драма', 'мистика'],
     'actors': ['Леонардо ДиКаприо'], 'release_date': '2010-02-19', 'duration': 138},

    # Марго Робби
    {'title': 'Отряд самоубийц', 'director': 'Дэвид Эйр', 'genres': ['экшн', 'приключения'], 'actors': ['Марго Робби'],
     'release_date': '2016-08-05', 'duration': 123},
    {'title': 'Тоня против всех', 'director': 'Крейг Гилеспи', 'genres': ['драма', 'биография', 'спорт'],
     'actors': ['Марго Робби'], 'release_date': '2017-12-08', 'duration': 120},
    {'title': 'Бамблби', 'director': 'Трэвис Найт', 'genres': ['фантастика', 'экшн'], 'actors': ['Марго Робби'],
     'release_date': '2018-12-21', 'duration': 114},
    {'title': 'Волк с Уолл-стрит', 'director': 'Мартин Скорсезе', 'genres': ['комедия', 'биография', 'драма'],
     'actors': ['Марго Робби'], 'release_date': '2013-12-25', 'duration': 180},

    # Анджелина Джоли
    {'title': 'Мистер и миссис Смит', 'director': 'Даг Лайман', 'genres': ['экшн', 'комедия', 'романтика'],
     'actors': ['Анджелина Джоли'], 'release_date': '2005-06-10', 'duration': 120},
    {'title': 'Лара Крофт: Расхитительница гробниц', 'director': 'Саймон Уэст', 'genres': ['экшн', 'приключения'],
     'actors': ['Анджелина Джоли'], 'release_date': '2001-06-15', 'duration': 100},
    {'title': 'Прерванная жизнь', 'director': 'Джеймс Манголд', 'genres': ['драма', 'биография'],
     'actors': ['Анджелина Джоли'], 'release_date': '1999-12-08', 'duration': 127},
    {'title': 'Малефисента', 'director': 'Роберт Стромберг', 'genres': ['фэнтези', 'приключения'],
     'actors': ['Анджелина Джоли'], 'release_date': '2014-05-30', 'duration': 97},

    # Меган Фокс
    {'title': 'Трансформеры', 'director': ' Майкл Бэй', 'genres': ['фантастика', 'экшн'], 'actors': ['Меган Фокс'],
     'release_date': '2007-07-03', 'duration': 144},
    {'title': 'Ниндзя-убийца', 'director': 'Джеймс МакТиг', 'genres': ['экшн', 'боевик'], 'actors': ['Меган Фокс'],
     'release_date': '2009-11-25', 'duration': 99},
]