name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: build docker image
      run: docker build -t cinema .
    - name: run docker container
      run: docker run -d -p 8080:8080 cinema
    - name: wait for container to start
      run: sleep 10
    - name: test app endpoint
      run: | 
        response=$(curl -s http://localhost:8080)
        echo "Response: $response"
    - name: stop container
      run: docker stop cinema && docker rm cinema